t_x = (0:length(x)-1) / Fx;
t_y_fir = (0:length(y_fir)-1) / Fy;
t_y_iir = (0:length(y_iir)-1) / Fy;
figure('Name', 'Σύγκριση Κυματομορφών Στο Πεδίο του Χρόνου');
subplot(3,1,1);
plot(t_x, x);
title('Αρχικό Ακουστικό Σήμα x(t) - Fs = 48 kHz');
xlabel('Χρόνος (sec)'); ylabel('Πλάτος');
grid on;
subplot(3,1,2);
plot(t_y_fir, y_fir);
title('Τελικό Σήμα y_{FIR}(t) με FIR Filter - Fs = 18 kHz');
xlabel('Χρόνος (sec)'); ylabel('Πλάτος');
grid on;
subplot(3,1,3);
plot(t_y_iir, y_iir);
title('Τελικό Σήμα y_{IIR}(t) με Butterworth Filter - Fs = 18 kHz');
xlabel('Χρόνος (sec)'); ylabel('Πλάτος');
grid on;