Fx = 48000;
L = 3;
F_int = L * Fx;
Wn = 0.125;
N_fir = 64;
h_fir = L * fir1(N_fir, Wn, 'low', hamming(N_fir+1));
[H_fir, f_fir] = freqz(h_fir, 1, 1024, F_int);
figure('Name', 'Υλοποίηση i: FIR Filter');
subplot(3,1,1);
impz(h_fir);
title('Κρουστική Απόκριση h[n] - FIR');
subplot(3,1,2);
plot(f_fir, abs(H_fir), 'b', 'LineWidth', 1.5);
title('Απόκριση Πλάτους |H(f)| - Δεκαδική Κλίμακα - FIR');
xlabel('Συχνότητα (Hz)'); ylabel('Πλάτος');
grid on;
subplot(3,1,3);
plot(f_fir, 20*log10(abs(H_fir)), 'r', 'LineWidth', 1.5);
title('Απόκριση Πλάτους 20log|H(f)| - Λογαριθμική Κλίμακα dB - FIR');
xlabel('Συχνότητα (Hz)'); ylabel('Πλάτος (dB)');
grid on;
N_iir = 6;
[b_iir, a_iir] = butter(N_iir, Wn, 'low');
b_iir = L * b_iir;
[H_iir, f_iir] = freqz(b_iir, a_iir, 1024, F_int);
figure('Name', 'Υλοποίηση ii:v Butterworth Filter');
subplot(3,1,1);
impz(b_iir, a_iir);
title('Κρουστική Απόκριση h[n] - Butterworth');
subplot(3,1,2);
plot(f_iir, abs(H_iir), 'b', 'LineWidth', 1.5);
title('Απόκριση Πλάτους |H(f)| - Δεκαδική Κλίμακα - Butterworth');
xlabel('Συχνότητα (Hz)'); ylabel('Πλάτος');
grid on;
subplot(3,1,3);
plot(f_iir, 20*log10(abs(H_iir)), 'r', 'LineWidth', 1.5);
title('Απόκριση Πλάτους 20log|H(f)| - Λογαριθμική Κλίμακα dB - Butterworth');
xlabel('Συχνότητα (Hz)'); ylabel('Πλάτος (dB)');
grid on;